Feature/add v4l2 pcie driver recipe
RidgeRun/meta-ridgerun-legacy pull request #10
Opened 2019-06-12 15:13 UTC by lleoncr

This feature adds the recipe for compiling the driver module for FPGA accelerators connected through PCI-e with V4L2 support.

2019-06-12 15:18 UTC, emmadrigal approved these changes

2019-06-12 17:21 UTC, mmadrigal requested changes

2019-06-12 17:21 UTC, mmadrigal commented on recipes-kernel/pcie-fpga-v4l2/pcie-fpga-v4l2_0.1.0.bb
> +FILES_${PN} += "${libdir}/*"
Usually, here we specify the exact file names to avoid copying unnecessary files. Please check you are not copying anything useless here.  * is normally dangerous!

2019-06-12 17:21 UTC, mmadrigal commented on recipes-kernel/pcie-fpga-v4l2/pcie-fpga-v4l2_0.1.0.bb
> +DESCRIPTION = "Allows to send and retrieve data using Video for Linux from FPGA graphics accelerators connected through PCI-e using DMA transfers"
I just would change "Video for Linux" for "V4L2 API"

2019-06-12 17:21 UTC, mmadrigal commented on recipes-kernel/pcie-fpga-v4l2/pcie-fpga-v4l2_0.1.0.bb
> +do_install () {
module class usually takes care of the installation, is there any reason for this additional installation sequence?

2019-06-12 17:47 UTC, lleoncr commented on recipes-kernel/pcie-fpga-v4l2/pcie-fpga-v4l2_0.1.0.bb
> +do_install () {
Yes, there is. The module is not installed in the image. So, copying the module to the kernel modules folders guarantee that the module is going to be inserted during IMX booting.

Also, I have tried deleting those lines and effectively, the image did not contain the module.

2019-06-12 18:18 UTC, dgarbanzo approved these changes

2019-06-13 13:25 UTC, mmadrigal commented on recipes-kernel/pcie-fpga-v4l2/pcie-fpga-v4l2_0.1.0.bb
> +do_install () {
I see the module's makefile does not call modules_install which is the one in charge of installing the modules at the kernel side:

https://www.kernel.org/doc/Documentation/kbuild/modules.txt           # Section 2

This is why the modules class is not able to install the module automatically.

2019-06-13 13:28 UTC, mmadrigal approved these changes

2019-06-13 14:03 UTC, lleoncr commented on recipes-kernel/pcie-fpga-v4l2/pcie-fpga-v4l2_0.1.0.bb
> +do_install () {
Ok. Good to know :+1:

2019-06-13 14:05 UTC, merged