Added the recipe for gst-perf on recipes-multimedia/gstreamer
RidgeRun/meta-ridgerun-legacy pull request #14
Opened 2019-07-09 15:05 UTC by fasm22

2019-07-09 15:20 UTC, adriancervantes commented
Change commit name to "Add recipe for gst-perf on recipes-multimedia/gstreamer"

2019-07-09 15:34 UTC, adriancervantes requested changes

2019-07-09 15:34 UTC, adriancervantes commented on recipes-multimedia/gstreamer/gst-perf_1.0.bb
> +SRC_URI = "file://gst-perf-${PV}.tar.gz"
Try to not use tarball, instead add the recipe to download the source code from [https://github.com/RidgeRun/gst-perf-autotools](https://github.com/RidgeRun/gst-perf-autotools) and remove files/gst-perf-1.0.tar.gz

2019-07-09 20:49 UTC, michaelgruner requested changes
We write commit messages in active voice. It should answer the following question: "If I apply this patch it will <your commit title>".

2019-07-10 20:00 UTC, michaelgruner approved these changes

2019-07-10 20:03 UTC, adriancervantes approved these changes

2019-07-10 20:06 UTC, merged