Update SRCDEV on gstd recipe to fetch release v0.14.0
RidgeRun/meta-ridgerun-legacy pull request #53
Opened 2022-07-29 13:44 UTC by msanch3z

Updated gstd recipe to fetch the latest version.

2022-08-03 19:57 UTC, edisonf requested changes

2022-08-03 19:57 UTC, edisonf commented on recipes-multimedia/gstreamer/gstd_1.0.bb
> +SRCREV = "bccdf2426d7efdb8009794c4dedcee31b4c85302"
Can we rename the recipe to include the actual version of gstd and use `${PV}` to fetch the actual version?

2022-08-11 14:24 UTC, msanch3z commented on recipes-multimedia/gstreamer/gstd_1.0.bb
> +SRCREV = "bccdf2426d7efdb8009794c4dedcee31b4c85302"
Agreed, new changes applied as requested

2022-08-11 15:01 UTC, edisonf approved these changes

2022-08-16 14:01 UTC, merged