Feature/add emboverlay recipe
RidgeRun/meta-ridgerun-legacy pull request #6
Opened 2018-05-08 21:17 UTC by eramirez392

2018-05-08 21:56 UTC, carlos-aguero approved these changes

2018-05-08 22:57 UTC, rrcarlosrodriguez approved these changes

2018-05-09 16:08 UTC, michaelgruner requested changes

2018-05-09 16:08 UTC, michaelgruner commented on recipes-multimedia/gstreamer/gst-emboverlay_1.0.bb
> +inherit autotools pkgconfig gettext
Always leave a new-line at the end of the file.

2018-05-09 16:08 UTC, michaelgruner commented on recipes-multimedia/gstreamer/gst-emboverlay_1.0.bb
> +DESCRIPTION = "GStreamer element used to overlay images and text over video streams or photos"
I would remove "or photos"

2018-05-09 16:23 UTC, merged